version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: production
    environment:
      NODE_ENV: production
      API_PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION:-us-east-1}
      S3_FORCE_PATH_STYLE: ${S3_FORCE_PATH_STYLE:-true}
      JWT_SECRET: ${JWT_SECRET}
      SEED_ADMIN_EMAIL: ${SEED_ADMIN_EMAIL:-admin@timon.ma.gov.br}
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD:-admin@123}
    volumes: []

  portal:
    build:
      context: .
      dockerfile: apps/frontend/portal/Dockerfile
      target: production
    environment:
      NODE_ENV: production
      PORT: ${PORTAL_PORT:-3000}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_CDN_BASE_URL: ${NEXT_PUBLIC_CDN_BASE_URL}
    ports: []
    volumes: []

  admin:
    build:
      context: .
      dockerfile: apps/frontend/admin/Dockerfile
      target: production
    environment:
      NODE_ENV: production
      PORT: ${ADMIN_PORT:-3100}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_CDN_BASE_URL: ${NEXT_PUBLIC_CDN_BASE_URL}
    ports: []
    volumes: []

  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
