version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timon-cms-postgres
    environment:
      POSTGRES_DB: cms
      POSTGRES_USER: cms
      POSTGRES_PASSWORD: cms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - timon-cms

  redis:
    image: redis:7-alpine
    container_name: timon-cms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - timon-cms
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: timon-cms-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - timon-cms
    command: server /data --console-address ":9001"

  # Criar bucket automaticamente
  createbuckets:
    image: minio/mc:latest
    container_name: timon-cms-minio-setup
    depends_on:
      - minio
    networks:
      - timon-cms
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/uploads;
      /usr/bin/mc anonymous set public myminio/uploads;
      exit 0;
      "

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  timon-cms:
    driver: bridge